<?php
/**
 * @file
 * Code for the dkan_sitewide_demo_front feature.
 */

include_once 'dkan_sitewide_demo_front.features.inc';

/**
 * Implements hook_block_info().
 */
function dkan_sitewide_demo_front_block_info() {
  $blocks['dkan_demo_front'] = array(
    'info' => t('Welcome to Open Data Kosovo Data Catalog'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['dkan_search_front'] = array(
    'info' => t('Search Your Data'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['dkan_add_front'] = array(
    'info' => t('Add a Dataset'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function dkan_sitewide_demo_front_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'dkan_demo_front':
      $block['subject'] = t('Welcome to Open Data Kosovo Data Catalog');
      $block['content'] = dkan_demo_front_block();
      break;

    case 'dkan_search_front':
      $block['subject'] = t('Search Your Data');
      $block['content'] = dkan_search_front_block();
      break;

    case 'dkan_add_front':
      $block['subject'] = t('Add a Dataset');
      $block['content'] = dkan_add_front_block();
      break;
  }
  return $block;
}

/**
 * Creates placeholder front block.
 */
function dkan_demo_front_block() {
  $dataset_url = url('dataset');
  $homepage_graphic = url(drupal_get_path('theme', 'dkan') . '/images/homepage-graphic.jpg');
  $homepage_dataset_url = url('dataset/gold-prices-london-1950-2008-monthly');
  $content = '<div class="module-content">
    <header>
     <p>Welcome to Open Data Kosovo\'s data catalog.<br><br>Explore data collected by the various organizations listed in the <a href="' . url('groups') . '">Groups</a> page.</p>
    </header>
  </div>';
  return $content;
}

/**
 * Creates search block for front page.
 */
function dkan_search_front_block() {
  return dkan_sitewide_search_bar();
}

/**
 * Creates "Add a Dataset" block for front page.
 */
function dkan_add_front_block() {
  $output = '<div class="add content">';
  $output .= 'Use the search field to find data or navigate to the <a href="' . url('dataset') . '">Datasets</a> page to explore Kosovo\'s open data.';
  $output .= '</div><a class="close icon-remove-sign" href="#close"></a>';
  return $output;
}


/**
 * Implements hook_views_post_execute().
 */
function dkan_sitewide_demo_front_views_post_execute(&$view) {
  // This adds the list of datasets to the view of groups. The group nid is used
  // as an argument for group audience.
  if ($view->name == 'front_page_group_list' && ($view->current_display == 'block' || $view->current_display == 'block_2') && isset($view->result[0])) {
    $nid = $view->result[0]->nid;
    $group_nodes = views_embed_view('front_page_group_list', 'block_1', $nid);
    $view->attachment_after = $group_nodes;
  }
}
